version: '2'

services:
  eruditus:
    build: .
    image: eruditus:latest
    container_name: eruditus
    restart: unless-stopped
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    volumes:
      - .data:/data/db
